# Generated by Django 5.0.2 on 2024-02-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_img',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Add Image to your Article.'),
        ),
    ]
