# Generated by Django 5.0.2 on 2024-03-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_station',
            field=models.CharField(default=0, max_length=2, verbose_name='station'),
            preserve_default=False,
        ),
    ]
