# Generated by Django 5.0.2 on 2024-03-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_comment_comment_station'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
